import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        flex:1,
        paddingTop:40,
        backgroundColor:"#fff",
        alignItems:'center',
        justifyContent:'space-between'
    },
    image:{
        marginBottom:20
    },  
    input:{
        width:'100%',
        marginBottom:20
    },
    button:{
        width:'80%',
        marginBottom:20
    },
    btnTxt:{
        fontSize:25
    },
    progress:{
        marginTop:10,
        width:300,
        height:20,
        borderRadius:5
    },
    form:{
        flex:1,
        width:'80%'
    },
    footer:{
        marginBottom:15,
        alignItems:'center'
    }
})